#!/bin/bash
docker run -it -p 3388:3388 \
	  -v $(pwd)/shared/shared:/home/judger/shared \
	  -v $(pwd)/shared/data:/home/judger/data \
	  --cap-add SYS_PTRACE \
	  --name tuoj-sandbox tuoj-sandbox-image:2.1

