#!/bin/bash 
docker run -it -p 3388:3388 \
	-v /Users/toby/Workspace/tuoj/judger/utils/sandbox/shared/shared:/home/judger/shared \
	-v /Users/toby/Workspace/tuoj/judger/utils/sandbox/shared/data:/home/judger/data \
	--name tuoj-sandbox tuoj-sandbox-image:2.1
